#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

FILE_PATH="src/repositories/owner_repository.rs"

cd $SOURCE_DIR

git checkout $FILE_PATH

exit 0