#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

cd $SOURCE_DIR

cargo test pet_can_be_created || fail-message "Did you implemented the right query for Owner insertion?"


