#!/bin/bash


##############
### Build the dev environment
##############
# Update and install necessary packages
echo "Updating and installing build-essential..."
sudo apt update -y
sudo apt install build-essential screen -y
docker network create \
  --driver bridge \
  --subnet 10.9.8.0/24 \
  --gateway 10.9.8.1 \
  --opt com.docker.network.bridge.name=scylla-dc \
  --ipv6=false \
  scylla-dc

images=(
    "scylladb/scylla:6.1"
    "prom/prometheus:v2.53.1"
    "grafana/grafana:11.1.4"
)

# Function to replace a query in a file
replace_query() {
    local FILE_PATH=$1
    local QUERY=$2

    if [ -f "$FILE_PATH" ]; then
        sed -i "s/$QUERY//g" "$FILE_PATH"
        echo "Query replaced successfully in $FILE_PATH"
    else
        echo "File $FILE_PATH does not exist."
    fi
}

# Function to download a Docker image
download_image() {
    image=$1
    echo "Downloading $image..."
    docker pull --quiet $image &
}

# Loop through the images array and download each one in the background
for image in "${images[@]}"; do
    download_image $image
done

wait

##################################
### Starting Scylla Monitoring ###
##################################

cd /root
ssh-keyscan github.com >> ~/.ssh/known_hosts
git clone https://github.com/scylladb/scylla-monitoring.git
cd scylla-monitoring
git checkout branch-5.8

cat << EOF > prometheus/scylla_servers.yml
- targets:
       - scylla-dc1-n1
       - scylla-dc1-n2
       - scylla-dc1-n3
  labels:
       cluster: cluster1
       dc: dc1
- targets:
       - scylla-dc2-n1
       - scylla-dc2-n2
       - scylla-dc2-n3
  labels:
       cluster: cluster1
       dc: dc2
EOF

./start-all.sh -v 6.0 -s prometheus/scylla_servers.yml --no-loki --no-alertmanager --no-renderer -D "--network scylla-dc"

# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source ~/.bashrc

# Clone the carepet-rust repository
cd /root
git clone https://github.com/DanielHe4rt/twitter-scylladb-rust-university.git university

# Build the carepet-rust project
echo "Building carepet-rust project..."
cd university
git checkout feat/instruqt-lab
screen -dmS rust cargo build &
echo "Build completed."
############################
### End of Dev Env
############################

echo "Script execution completed."

echo fs.aio-max-nr=1048576 | sudo tee /etc/sysctl.d/41-aio_max_nr.conf && sudo sysctl -p /etc/sysctl.d/41-aio_max_nr.conf

exit 0