#!/bin/bash


##############
### Build the dev environment
##############
# Update and install necessary packages
echo "Updating and installing build-essential..."
sudo apt update -y
sudo apt install build-essential screen -y
docker network create --driver bridge ws-scylla

images=(
    "scylladb/scylla:6.1"
    "prom/prometheus:v2.53.1"
    "grafana/grafana:11.1.4"
)

# Function to replace a query in a file
replace_query() {
    local FILE_PATH=$1
    local QUERY=$2

    if [ -f "$FILE_PATH" ]; then
        sed -i "s/$QUERY//g" "$FILE_PATH"
        echo "Query replaced successfully in $FILE_PATH"
    else
        echo "File $FILE_PATH does not exist."
    fi
}

# Function to download a Docker image
download_image() {
    image=$1
    echo "Downloading $image..."
    docker pull $image &
}

# Loop through the images array and download each one in the background
for image in "${images[@]}"; do
    download_image $image
done

wait

##################################
### Starting Scylla Monitoring ###
##################################

cd /root
ssh-keyscan github.com >> ~/.ssh/known_hosts
git clone https://github.com/scylladb/scylla-monitoring.git
cd scylla-monitoring
git checkout branch-5.8

MONITORING_YML="https://gist.githubusercontent.com/DanielHe4rt/ea49140ed78153ba4a34f141c5e98422/raw/2c1db20fc32c00c769b91fd7e1135e525a42d85b/scylla_servers.yml"

wget --tries=3 --waitretry=3 $MONITORING_YML --output-document=prometheus/scylla_servers.yml

./start-all.sh -v 6.0 -s prometheus/scylla_servers.yml --no-loki --no-alertmanager --no-renderer -D "--network ws-scylla"

# Install Rust
echo "Installing Rust..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source ~/.bashrc

# Clone the carepet-rust repository
echo "Cloning carepet-rust repository..."
cd /root
git clone https://github.com/DanielHe4rt/twitter-scylladb-rust-university.git

# Build the carepet-rust project
echo "Building carepet-rust project..."
cd carepet-rust
screen -dmS rust cargo build 
echo "Build completed."

# Replace queries in the specified files
echo "Replacing queries in repository files..."
replace_query "src/repositories/owner_repository.rs" "INSERT INTO owners (owner_id, name, address) VALUES (?, ?, ?)"
replace_query "src/repositories/pet_repository.rs" "INSERT INTO pets (owner_id, pet_id) VALUES (?, ?)"

############################
### End of Dev Env
############################

echo "Script execution completed."

echo fs.aio-max-nr=1048576 | sudo tee /etc/sysctl.d/41-aio_max_nr.conf && sudo sysctl -p /etc/sysctl.d/41-aio_max_nr.conf

exit 0