#!/bin/bash

##############
### Build the dev environment
##############

# Update and install necessary packages
echo "Updating and installing build-essential..."
sudo apt update -y
sudo apt install build-essential screen libssl-dev pkg-config -y

# Create Docker network
docker network create --driver bridge --subnet 10.9.8.0/24 --gateway 10.9.8.1 --opt com.docker.network.bridge.name=scylla-dc --ipv6=false scylla-dc &

# Pull Docker images in parallel
images=(
    "prom/prometheus:v2.53.1"
    "grafana/grafana:11.1.4"
    "scylladb/scylla:6.1"
)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &
for image in "${images[@]}"; do
    docker pull --quiet $image &
done

wait  # Wait for all Docker pulls to finish

##################################
### Starting Scylla Monitoring ###
##################################

# Clone the Scylla monitoring repo in the background
cd /root
ssh-keyscan github.com >> ~/.ssh/known_hosts &
git clone https://github.com/scylladb/scylla-monitoring.git &
wait  # Wait for cloning and ssh-keyscan

cd scylla-monitoring
git checkout branch-5.8

# Write the scylla_servers.yml configuration
cat << EOF > prometheus/scylla_servers.yml
- targets:
       - scylla-dc1-n1
       - scylla-dc1-n2
       - scylla-dc1-n3
  labels:
       cluster: cluster1
       dc: dc1
- targets:
       - scylla-dc2-n1
       - scylla-dc2-n2
       - scylla-dc2-n3
  labels:
       cluster: cluster1
       dc: dc2
EOF

# Start Scylla monitoring in the background
./start-all.sh -v 6.0 -s prometheus/scylla_servers.yml --no-loki --no-alertmanager --no-renderer -D "--network scylla-dc" &

# Install Rust in the background
wait  # Wait for Rust to install

source ~/.bashrc

# Clone and build the carepet-rust project in the background
cd /root
git clone https://github.com/DanielHe4rt/twitter-scylladb-rust-university.git university &
wait  # Wait for cloning

cd university
git checkout feat/instruqt-lab
screen -dmS rust cargo run &

############################
### End of Dev Env
############################

# Tuning system settings in the background
echo fs.aio-max-nr=1048576 | sudo tee /etc/sysctl.d/41-aio_max_nr.conf && sudo sysctl -p /etc/sysctl.d/41-aio_max_nr.conf &

# Completion message
echo "Script execution completed."

exit 0